## deploy target destination path and filename
target = .zshrc
## specify subdirectory if necessary
# subdirectory = .config

## files in resources/deploy/filename_of_this_file will be concatenate into target file in your home directory
## filename should not contain '='

basic_config
aliases
dircolors
history_search
auto_ls_after_cd
ubuntu_1604_JSK_envs
#autoattach_tmux

#prompt
zplug_with_pure
#prompt_pure
#fzf-z-search
#fzf-autocompletion
